# Generated by Django 5.2.5 on 2025-10-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesa_capacidad_orden_ordendetalle'),
        ('platillos', '0002_platillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetalle',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordendetalle',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='platillos.platillo'),
        ),
    ]
